### ISSUE TITLE
get_node_selectionboxes crashes for MineClone 2 vines

### ISSUE THREAD

**Issue by grorp** [appgurueu/modlib#10]
`modlib.minetest.get_node_selectionboxes` crashes if you execute it on MineClone 2 vines (`mcl_core:vine`).

Minetest version: `5.6.1`
MineClone 2 version: `0.82.0`
Modlib version: `rolling-100`

**Steps to reproduce**

Put this tool into a mod that depends on Modlib:

``` Lua
minetest.register_tool(":modlib:crash_tester", {
	description = "Modlib Crash Tester",
	on_use = function(itemstack, player, pointed_thing)
		if pointed_thing.type == "node" then
			modlib.minetest.get_node_selectionboxes(pointed_thing.under)
		end
	end,
})
```
Start a MineClone2 world with that mod enabled. Find or place vines and punch them with the "Modlib Crash Tester" tool.

**Result**

The server crashes.

```
AsyncErr: Lua: Runtime error from mod 'modlib' in callback item_OnUse(): ...netest.Minetest/.minetest/mods/modlib/minetest/boxes.lua:71: attempt to index local 'box' (a nil value)
stack traceback:
	...netest.Minetest/.minetest/mods/modlib/minetest/boxes.lua:71: in function 'get_node_selectionboxes'
	...app/net.minetest.Minetest/.minetest/mods/modlib/init.lua:149: in function <...app/net.minetest.Minetest/.minetest/mods/modlib/init.lua:147>
```

**Expected result**

Nothing happens.

**Comment by appgurueu** [comment]
The docs say:

>     {
>         -- A box like the selection box for torches
>         -- (wallmounted param2 is used, if applicable)
>         type = "wallmounted",
>         wall_top = box,
>         wall_bottom = box,
>         wall_side = box
>     }

But Mineclone2 does:

> `selection_box = {type = "wallmounted"}`

Clear issue on Mineclone's part IMO - they are relying on undocumented features. I've got a related TODO however:

> `-- TODO complete if only wall_top is given`

But they aren't even providing `wall_top` here.

I'll dig into the engine sources to figure out how the engine deals with this. Edit: The engine provides the following (of course undocumented!) defaults:

> 	// default is sign/ladder-like
> 	wall_top = aabb3f(-BS/2, BS/2-BS/16., -BS/2, BS/2, BS/2, BS/2);
> 	wall_bottom = aabb3f(-BS/2, -BS/2, -BS/2, BS/2, -BS/2+BS/16., BS/2);
> 	wall_side = aabb3f(-BS/2, -BS/2, -BS/2, -BS/2+BS/16., BS/2, BS/2);

Implementing these.

**Comment by appgurueu** [comment]
Should be fixed in https://github.com/appgurueu/modlib/commit/785dcb80f4a81ca32fbda129716501ebdf6b675e. Thanks for the report!

**Comment by grorp** [comment]
Thank you for the quick fix :)
