### ISSUE TITLE
Add LuaCheck

### ISSUE THREAD

**Issue by Panquesito7** [appgurueu/modlib#12]

**Comment by appgurueu** [comment]
See https://github.com/appgurueu/modlib/issues/11#issuecomment-1501564405; the issue still persists. This is effectively a duplicate.

I won't bring modlib into a style LuaCheck accepts; not only would that be very tedious, it would also be very error prone.

However, there is one new consideration: I might consider modifying LuaCheck to deal with `setfenv` (at least my special use case) once I find the time for it.

**Comment by Panquesito7** [comment]
Yeah, sorry, I forgot I've made an issue previously.
Will close, thank you.
