### ISSUE TITLE
Should not override `default` global variable where possible

### ISSUE THREAD

**Issue by ketwaroo** [appgurueu/modlib#17]
On https://github.com/appgurueu/modlib/blob/master/less_than.lua#L5 , `default` is being overriden with an empty table.

Instead should be something like `default = default or {}` to avoid losing existing `default` data.

or use  `if not minetest.global_exists("default") then ... `

Relates to https://codeberg.org/mineclonia/mineclonia/pulls/931#issuecomment-1416769 possible. Found an instance where modlib was included by another mod and may have caused crashes in other mods.

**Comment by appgurueu** [comment]
Thanks for the report. I'm afraid this is a false positive. The code in question is:

```lua
local less_than = {}
setfenv(1, less_than)
default = {}
...
return less_than
```

this is a namespacing pattern found all throughout modlib. Note the call to [`setfenv`](https://www.lua.org/manual/5.1/manual.html#pdf-setfenv). After it, the line `default = {}` doesn't write to the global table - instead, it writes to the `less_than` "module" table.
