### ISSUE TITLE
Not self documenting, please change readme/description. 

### ISSUE THREAD

**Issue by FatalistError** [appgurueu/modlib#6]
"Mostly self-documenting code. Mod namespace is modlib, containing all variables & functions."
None of this is self documenting, just state kindly that you have no documentation and that this mod is only for yourself, that way nobody makes the mistake of trying to figure this out, because they wont.

**Comment by appgurueu** [comment]
First of all, *some* parts are documented. I don't have no docs. Take a closer look at the Readme.

Second, define what you consider self-documenting code. I consider it self-documenting - when I want to find out the specifics of how to call a function, I just glance at the code. It's strictly organized hierarchically, i.e. each file is for an environment with the given name. I do want to generate proper docs out of the outline eventually. Perhaps I should emphasize that this is first and foremost for myself, yet everybody else can see for themselves whether it may be useful to them too.

Perhaps I should point towards the tests I have for this, they provide good examples for how to use some of the funcs.
